python_sources = [
  '__init__.py',
  'adaptahop.py',
  'ahf.py',
  'hbtplus.py',
  'hop.py',
  'number_array.py',
  'rockstar.py',
  'subfind.py',
  'subfindhdf.py',
  'subhalo_catalogue.py',
  'velociraptor.py',
]

py.install_sources(
  python_sources,
  subdir: 'pynbody/halo',
)

subdir('details')
