python_sources = [
  '__init__.py',
  'configuration.py',
  'dependencytracker.py',
  'derived.py',
  'family.py',
  'simdict.py',
  'transformation.py',
  'units.py',
  'default_config.ini',
]

py.install_sources(
  python_sources,
  subdir: 'pynbody',
)

subdir('analysis')
subdir('array')
subdir('plot')
subdir('gravity')
subdir('chunk')
subdir('filt')
subdir('sph')
subdir('snapshot')
subdir('bridge')
subdir('halo')
subdir('extern')
subdir('kdtree')
subdir('test_utils')
subdir('util')
