python_sources = [
  '__init__.py',
  'ascii.py',
  'copy_on_access.py',
  'gadget.py',
  'gadgethdf.py',
  'grafic.py',
  'namemapper.py',
  'nchilada.py',
  'ramses.py',
  'simsnap.py',
  'subsnap.py',
  'swift.py',
  'tipsy.py',
  'util.py',
]

py.install_sources(
  python_sources,
  subdir: 'pynbody/snapshot',
)
